apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-ns-cfgmgr2
spec:
  template:
    metadata:
      labels:
        app: k8s-ns-cfgmgr2
    spec:
      serviceAccountName: k8s-ns-cfgmgr
      containers:
        - name:  k8s-2-cfgmgr
          image: r00tsh3ll/k8s-ns-cfgmgr
          imagePullPolicy: Always
          env:
          - name: URL
            value: "https://github.com/alyarctiq/go-git.git"
          - name: FOLDER
            value: "."
          - name: NAMESPACE
            value: "hipster2"            
