apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-ns-cfgmgr
spec:
  template:
    metadata:
      labels:
        app: k8s-ns-cfgmgr
    spec:
      serviceAccountName: k8s-ns-cfgmgr
      containers:
        - name:  k8s-ns-cfgmgr
          image: r00tsh3ll/k8s-ns-cfgmgr
          imagePullPolicy: Always
          env:
          - name: URL
            value: "https://github.com/alyarctiq/k8s-ns-cfgmgr.git"
          - name: FOLDER
            value: "/yamls"
          - name: NAMESPACE
            value: "hipster"            
