apiVersion: v1
kind: ServiceAccount
metadata:
 name: k8s-ns-cfgmgr
 namespace: hipster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-ns-cfgmgr
  namespace: hipster # Should be namespace you are granting access to
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-ns-cfgmgr
  namespace: hipster # Should be namespace you are granting access to
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-ns-cfgmgr # Should match name of Role
subjects:
- namespace: source # Should match namespace where SA lives
  kind: ServiceAccount
  name: k8s-ns-cfgmgr # Should match service account name, above
